name: Supabase Activity Scheduler

on:
  schedule:
    - cron: '0 0 * * 0,3' # 매주 일요일, 수요일 오전 0시에 실행됩니다
  workflow_dispatch:

jobs:
  send-http-request:
    runs-on: ubuntu-latest

    steps:
      - name: Send HTTP Request
        run: |
          curl -H "X-GitHub-Action: true" https://work-connect-plum.vercel.app/api/etc/activity-scheduler
